data_file = "src/chains.json"
public_dir = "public"
qr_dir = "public/qr"

[verifier]
name = "michalis"
public_key = "847074f1fb351eaa06337823c68f2a9fb28c98db976bc5cc16867e4b84bc1060"

[[chains]]
name = "polkadot"
rpc_endpoint = "wss://rpc.polkadot.io"

[[chains]]
name = "kusama"
rpc_endpoint = "wss://kusama-rpc.polkadot.io"

[[chains]]
name = "westend"
rpc_endpoint = "wss://westend-rpc.polkadot.io"

[[chains]]
name = "statemine"
rpc_endpoint = "wss://statemine-rpc.polkadot.io"

[[chains]]
name = "statemint"
rpc_endpoint = "wss://statemint-rpc.polkadot.io"
