data_file = "public/data.json"
public_dir = "public"
qr_dir = "public/qr"

[verifier]
name = "michalis"
public_key = "847074f1fb351eaa06337823c68f2a9fb28c98db976bc5cc16867e4b84bc1060"

# Optional. Only used when updating from GitHub releases
[github]
owner = "paritytech"
repo = "polkadot"

[[chains]]
name = "polkadot"
rpc_endpoint = "wss://rpc.polkadot.io"
# Optional. Only used when updating from GitHub releases
genesis_hash = "0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3"

[[chains]]
name = "kusama"
rpc_endpoint = "wss://kusama-rpc.polkadot.io"
# Optional. Only used when updating from GitHub releases
genesis_hash = "0xb0a8d493285c2df73290dfb7e61f870f17b41801197a149ca93654499ea3dafe"

[[chains]]
name = "westend"
rpc_endpoint = "wss://westend-rpc.polkadot.io"
<<<<<<< HEAD

[[chains]]
name = "statemine"
rpc_endpoint = "wss://statemine-rpc.polkadot.io"

[[chains]]
name = "statemint"
rpc_endpoint = "wss://statemint-rpc.polkadot.io"
=======
# Optional. Only used when updating from GitHub releases
genesis_hash = "0xe143f23803ac50e8f6f8e62695d1ce9e4e1d68aa36c1cd2cfd15340213f3423e"
>>>>>>> 880098b76c02a81e3b95901d6421eefed8df7ea4
